import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/navbar';
import { host, inter, header, combo, italiana, dosis } from './ui/fonts';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${italiana.variable} ${dosis.variable}`}>
        <Navbar />
        <main className='min-h-screen max-w-7xl mx-auto px-4 py-8'>
          {children}
        </main>
      </body>
    </html>
  );
}
